options_possible_text_fields_list = [
    ["first", "1st", "one", "burst", "1", "search file", "search files", "file search", "files search", "search pile"],
    ["second", "2nd", "two", "too", "hecand", "2", "transfer file", "transfer files", "file transfer", "files transfer", "transfer pile"],
    ["third", "3rd", "three", "herd", "3", "open file", "open files", "file open", "files open", "open pile", "opan file"],
    ["fourth", "4th", "four", "forth", "4", "search folder", "search folders", "folder search", "folder search", "search holder"],
    ["fifth", "5th", "five", "fiveth", "hive", "5", "transfer folder", "transfer folders", "folder transfer", "folders transfer", "transfer holder"],
    ["sixth", "6th", "six", "wix", "mix", "mixed", "6", "filter file", "filter files", "file filter", "files filter", "filter fine"],
    ["seventh", "7th", "seven", "even", "7", "create file", "create files", "file create", "files create", "create pile", "ate file"],
    ["eighth", "8th", "eight", "ate", "8", "create folder", "create folders", "folder create", "folders create", "ate folder"],
]

search_file_possible_options_list = [
    ["first", "1st", "1", "one", "burst", "exact name", "exact"],
    ["second", "2nd", "two", "too", "hecand", "2", "search by name", "name", "search by fame", "harsh by name"],
]

possible_file_filters = [
    "greater than",
    "greater than equal to",
    "less than",
    "less than equal to",
    "equal to",
    "not equal to",
    "group by",
    "aggregate"
]

possible_aggregate_operations = [
    "sum",
    "mean",
    "max",
    "min",
    "count"
]

possible_file_extension_map = {
    "excel": "xlsx",
    "xlsx": "xlsx",
    "xl": "xlsx",
    "csv": "csv",
    "csb": "csv",
    "doc": "docx",
    "docx": "docx",
    "dcx": "docx",
    "png": "png",
    "ping": "png",
    "pnd": "png",
    "jpg": "jpg",
    "jpd": "jpg",
    "jpeg": "jpeg",
    "j peg": "jpeg",
    "json": "json",
    "jason": "json",
    "jsn": "json",
    "pdf": "pdf",
    "pdef": "pdf",
    "pkl": "pkl",
    "pickle": "pkl",
    "pickel": "pkl",
    "pptx": "pptx",
    "ppt": "pptx",
    "log": "log",
    "og": "log",
    "fog": "log",
    "loge": "log",
    "html": "html",
    "txt": "txt",
    "text": "txt",
    "parquet": "parquet",
    "park": "parquet",
    "parke": "parquet",
    "zip": "zip"
}

text_to_option_map = {
    "first": 1,
    "one": 1,
    "option first": 1,
    "1st": 1,
    "option first search file": 1,
    "option first search": 1,
    "option one search": 1,
    "option one": 1,
    "search file": 1,
    "first search": 1,
    "first search file": 1,
    "first file search": 1,
    "first file": 1,
    "file first": 1,
    "search one": 1,
    "option search file": 1,
    "search file option": 1,
    "file search option": 1,
    "option one search file": 1,
    "option one file search": 1,
    "one search file": 1,
    "1st search file": 1,
    "one file search": 1,
    "one file": 1,
    "search first": 1,
    "search file one": 1,
    "search file first": 1,
    "file search": 1,
    "second": 2,
    "two": 2,
    "2nd": 2,
    "option second": 2,
    "option second transfer file": 2,
    "option second transfer": 2,
    "option two transfer": 2,
    "option two": 2,
    "transfer file": 2,
    "second transfer": 2,
    "second transfer file": 2,
    "2nd transfer file": 2,
    "second file transfer": 2,
    "second file": 2,
    "file second": 2,
    "transfer two": 2,
    "option transfer file": 2,
    "transfer file option": 2,
    "file transfer option": 2,
    "option two transfer file": 2,
    "option two file transfer": 2,
    "two transfer file": 2,
    "two file transfer": 2,
    "two file": 2,
    "transfer second": 2,
    "search second": 2,
    "transfer file two": 2,
    "transfer file second": 2,
    "file transfer": 2,
    "third": 3,
    "three": 3,
    "3rd": 3,
    "option third": 3,
    "option third open file": 3,
    "option third open": 3,
    "option three open": 3,
    "option three": 3,
    "open file": 3,
    "third open": 3,
    "third open file": 3,
    "3rd open file": 3,
    "third file open": 3,
    "third file": 3,
    "file third": 3,
    "open three": 3,
    "option open file": 3,
    "open file option": 3,
    "file open option": 3,
    "option three open file": 3,
    "option three file open": 3,
    "three open file": 3,
    "three file open": 3,
    "three file": 3,
    "open third": 3,
    "open file three": 3,
    "open file third": 3,
    "file open": 3,
    "fourth": 4,
    "four": 4,
    "4th": 4,
    "option fourth": 4,
    "option fourth search folder": 4,
    "option fourth search": 4,
    "option four search": 4,
    "option four": 4,
    "search folder": 4,
    "fourth search": 4,
    "fourth search folder": 4,
    "4th search folder": 4,
    "fourth folder search": 4,
    "fourth folder": 4,
    "folder fourth": 4,
    "search four": 4,
    "option search folder": 4,
    "search folder option": 4,
    "folder search option": 4,
    "option four search folder": 4,
    "option four folder search": 4,
    "four search folder": 4,
    "four folder search": 4,
    "four folder": 4,
    "search fourth": 4,
    "search folder four": 4,
    "search folder fourth": 4,
    "folder search": 4,
    "fifth": 5,
    "five": 5,
    "5th": 5,
    "option fifth": 5,
    "option fifth transfer folder": 5,
    "option fifth transfer": 5,
    "option five transfer": 5,
    "option five": 5,
    "transfer folder": 5,
    "fifth transfer": 5,
    "fifth transfer folder": 5,
    "5th transfer folder": 5,
    "fifth folder transfer": 5,
    "fifth folder": 5,
    "folder fifth": 5,
    "transfer five": 5,
    "option transfer folder": 5,
    "transfer folder option": 5,
    "folder transfer option": 5,
    "option five transfer folder": 5,
    "option five folder transfer": 5,
    "five transfer folder": 5,
    "five folder transfer": 5,
    "five folder": 5,
    "transfer fifth": 5,
    "transfer folder five": 5,
    "transfer folder fifth": 5,
    "folder transfer": 5,
    "sixth": 6,
    "six": 6,
    "6th": 6,
    "option sixth": 6,
    "option sixth open folder": 6,
    "option sixth open": 6,
    "option six open": 6,
    "option six": 6,
    "open folder": 6,
    "sixth open": 6,
    "sixth open folder": 6,
    "sixth folder open": 6,
    "6th open folder": 6,
    "sixth folder": 6,
    "folder sixth": 6,
    "open six": 6,
    "option open folder": 6,
    "open folder option": 6,
    "folder open option": 6,
    "option six open folder": 6,
    "option six folder open": 6,
    "six open folder": 6,
    "six folder open": 6,
    "six folder": 6,
    "open sixth": 6,
    "open folder six": 6,
    "open folder sixth": 6,
    "folder open": 6,
    "seventh": 7,
    "seven": 7,
    "7th": 7,
    "option seventh": 7,
    "option seventh create file": 7,
    "option seventh create": 7,
    "option seven create": 7,
    "option seven": 7,
    "create file": 7,
    "grade file": 7,
    "seventh create": 7,
    "seventh create file": 7,
    "seventh grade file": 7,
    "7th create file": 7,
    "7th grade file": 7,
    "seventh file create": 7,
    "seventh file": 7,
    "file seventh": 7,
    "create seven": 7,
    "option create file": 7,
    "create file option": 7,
    "file create option": 7,
    "option seven create file": 7,
    "option seven file create": 7,
    "seven create file": 7,
    "seven file create": 7,
    "seven file": 7,
    "create seventh": 7,
    "create file seven": 7,
    "create file seventh": 7,
    "file create": 7,
    "eighth": 8,
    "eight": 8,
    "8th": 8,
    "option eighth": 8,
    "option eighth create folder": 8,
    "option eighth create": 8,
    "option eight create": 8,
    "option eight": 8,
    "create folder": 8,
    "grade folder": 8,
    "eighth create": 8,
    "eighth create folder": 8,
    "eighth grade folder": 8,
    "8th create folder": 8,
    "8th grade folder": 8,
    "eighth folder create": 8,
    "eighth folder": 8,
    "folder eighth": 8,
    "create eight": 8,
    "option create folder": 8,
    "create folder option": 8,
    "folder create option": 8,
    "option eight create folder": 8,
    "option eight folder create": 8,
    "eight create folder": 8,
    "eight folder create": 8,
    "eight folder": 8,
    "create eighth": 8,
    "create folder eight": 8,
    "create folder eighth": 8,
    "folder create": 8,
}